nana/core/urls.py
from django.conf.urls import patterns, url
from core import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'nana.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    
    url(r'^$', views.index, name='index'),
    url(r'^headlines/(?P<category_name>\w+)', views.headlines, name='headlines'),
    url(r'^my_summaries/', views.my_summaries, name='my_summaries'), 
    url(r'^add/', views.add_url, name='add_url'),
    url(r'^register/', views.register, name='register'),
    url(r'^login/', views.user_login, name='login'),
    url(r'^logout/', views.user_logout, name='logout'),
    url(r'^test/', views.test, name='test'),
    url(r'^search/', views.search, name='search'),
    url(r'^like/', views.like, name='like'),
    url(r'^remove/', views.remove, name='remove'),
    # url(r'^edit/', views.edit, name='edit'),

)

nana/nana/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'nana.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^nana/', include('core.urls'))
)

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}),)

nana/core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Headlines(models.Model):
    url = models.URLField(unique=True)
    comments = models.TextField(blank=True)
    title = models.TextField(blank=True)
    summary = models.TextField(blank=True)
    category = models.TextField(blank=True)
    published = models.DateTimeField(blank=True)    
    added = models.DateTimeField(auto_now_add=True)
    likes = models.IntegerField(default=0, blank=True)
    
    def __unicode__(self):
        return self.title

class Summaries(models.Model):
    user = models.ForeignKey(User)
    url = models.URLField(unique=True)
    comments = models.TextField(blank=True)
    title = models.TextField(blank=True)
    summary = models.TextField(blank=True)
    added = models.DateTimeField(auto_now_add=True)
    
    def __unicode__(self):
        return self.title

class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)

    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    # Override the __unicode__() method to return out something meaningful
    def __unicode__(self):
        return self.user.username

class Like(models.Model):
    # need to add related name because Django auto creates a reverse relation from Headlines and User back to Like
    # to reference Like withing Headline's instance, you must go h1.headline_like_by.all() etc.
    user = models.ForeignKey(User, null=True, default=None)
    headline = models.ManyToManyField(Headlines, null=True, default=None, related_name='headline_liked_by')
    date_added = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.user.username

nana/core/forms.py
from django import forms
from core.models import Headlines, UserProfile, Summaries
from django.contrib.auth.models import User

class HeadlinesForm(forms.ModelForm):
    url = forms.URLField(help_text="Please enter url.")
    comments = forms.CharField(help_text="Please enter any comments.", required=False)
    
    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if not url.startswith('http://'):
            url = 'http://' + url

        cleaned_data['url'] = url
        return cleaned_data

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Headlines
        fields = ('url', 'comments',)

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)

class SummariesForm(forms.ModelForm):
    url = forms.URLField(help_text="Please enter url.")
    comments = forms.CharField(help_text="Please enter any comments.", required=False)
    
    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if not url.startswith('http://'):
            url = 'http://' + url

        cleaned_data['url'] = url
        return cleaned_data

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Summaries
        fields = ('url', 'comments',)

nana/core/views.py
import random

# from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, StreamingHttpResponse
from django.template import RequestContext
from django.shortcuts import render_to_response, redirect
# from django.views.decorators.csrf import csrf_exempt #to disable csrf protection on view add @csrf_exempt
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from endless_pagination.decorators import page_template

from core.models import Headlines, Summaries, Like
from core.forms import UserForm, UserProfileForm, SummariesForm
from core.Smmry import Smmry
# Create your views here.

#helper functions
def clean_url(url):
    if not url.startswith('http://'):
        url = 'http://' + url
    return url



#url views
def test(request):
    pass

def index(request):
    return redirect('/nana/headlines/top')

@page_template('core/more_headlines.html')
def headlines(request, category_name, template='core/base.html', extra_context=None):
    context = RequestContext(request)

# topics
#    : top stories
#   w : world
#   n : us
#   b : business
#   tc : technology
#   e : entertainment
#   s : sports
#   snc : science

    category_options = {'top': ' ',
                        'world': 'w',
                        'us': 'n',
                        'business': 'b',
                        'technology': 'tc',
                        'media': 'e',
                        'sports': 's',
                        'science':'snc'
                        }

    category_key = category_options[category_name]
    if category_name == 'us':
        category_name = category_name.upper()
    else:
        category_name = category_name.capitalize()

    all_headlines = Headlines.objects.filter(category=category_key).order_by('-published')
    
    if extra_context is not None:
        context.update(extra_context)

    if request.user.is_authenticated():
        headlines = []
        for headline in all_headlines:
            headlines.append( (headline,
                               headline.headline_liked_by.filter(user=request.user) ) )

    else:
        headlines = []
        for headline in all_headlines:
            headlines.append( (headline, []))

    
    context_dict = {'headlines': headlines, 'headlines_template': True, 'category': category_name}

    return render_to_response(template, context_dict, context)

@page_template('core/more_user_summaries.html')
@login_required
def my_summaries(request, template='core/base.html', extra_context=None):
    context = RequestContext(request)
    form = SummariesForm()
    
    if request.user.is_authenticated():
        user_summaries = Summaries.objects.filter(user=request.user).order_by('-added')
    else:
        user_summaries = None

    if extra_context is not None:
        context.update(extra_context)

    context_dict = {'form': form, 
                    'user_summaries': user_summaries
                    }

    return render_to_response(template, context_dict, context)


@login_required
def add_url(request):
    context = RequestContext(request)
    user = request.user
    summary_dict = { }
    print request.method
    if request.method == 'POST':
        try:
            # make API call to Smmry
            key = random.choice(['3D3037D0E0', '4DBA02EDB7', '9F13AD87AD'])
            url = clean_url(request.POST['url'])
            smmry = Smmry(key)
            data = smmry.call_dict(url)

            comments = request.POST['comments']
            title = smmry.clean_response(data, field='sm_api_title')
            summary = smmry.clean_response(data, field='sm_api_content')

            # Just for the Ajax response, it displays as recent            

            page = Summaries(user=user, url=url, comments=comments, title=title, summary=summary)
            summary_dict = {'s': page}
            print page
            page.save()
     
        # if error for whatever reason
        except:
            url = clean_url(request.POST['url'])
            comments = request.POST['comments']
            title = url
            summary = 'Not Available'

            page = Summaries(user=user, url=url, comments=comments, title=title, summary=summary)
            summary_dict = {'s': page}
            page.save()

        # for testing only
        return render_to_response('core/latest_add.html', summary_dict, context)        

    else:
        return HttpResponse('There were errors!')

def register(request):
    context = RequestContext(request)
    registered = False
    password_mismatch = False

    if request.method == 'POST':
        if request.POST['password'] != request.POST['password2']:
            password_mismatch = True
            user_form = UserForm()
            profile_form = UserProfileForm()

        else:
            user_form = UserForm(data=request.POST)
            profile_form = UserProfileForm(data=request.POST)

            if user_form.is_valid() and profile_form.is_valid():
                user = user_form.save()
                # Has the password with the set_password method.
                # Once hashed, we can update the user object.
                user.set_password(user.password)
                user.save()

                # Sort out the UserProfile instance.  Set commit=False so that we can set user attribute
                profile = profile_form.save(commit=False)
                profile.user = user

                if 'picture' in request.FILES:
                    profile.picture = request.FILES['picture']

                profile.save()

                registered = True

            else:
                print user_form.errors, profile_form.errors

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render_to_response(
        'core/register.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered, 'password_mismatch': password_mismatch}, 
        context)

def user_login(request):
    context = RequestContext(request)
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        # Tests if provided username and password are correct
        user = authenticate(username=username, password=password)
        # If User object is returned, we have a User object
        if user is not None:
            # If the account is valid and active, we can log the user in.
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/nana/my_summaries/')
            else:
                return HttpResponse('Your account is disabled.')
        else:
            # Bad login details were provided. So we can't log the user in.
            print 'Invalid login details: {0}, {1}'.format(username, password)
            context_dict = {'bad_details': True}
            return render_to_response('core/login.html', context_dict, context)
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render_to_response('core/login.html', {}, context)

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/nana/')

def search(request):
    context = RequestContext(request)
    searched = request.POST['search']

    headlines = Headlines.objects.filter(Q(summary__icontains=searched) |
                                         Q(title__icontains=searched) |
                                         Q(comments__icontains=searched))

    if request.user.is_authenticated():
        results = True
        my_summaries = Summaries.objects.filter(Q(user=request.user), Q(summary__icontains=searched) |
                                         Q(title__icontains=searched))

        if len(my_summaries) == 0:
            results = False

    else:
        my_summaries = []
        results = False

    context_dict = {'headlines': headlines, 'searched': searched, 'results': results, 'my_summaries': my_summaries}
    return render_to_response('core/search.html', context_dict, context)


def like(request):
    headline_id = None
    user = None
    if request.method == 'GET':
        headline_id = request.GET['headline_id']
        user = request.user

    likes = 0

    if headline_id and user:
        headline = Headlines.objects.get(id=int(headline_id))
        liked_by = Like.objects.get_or_create(user=user)
        liked_by = Like.objects.get(user=user)

        if headline and liked_by:
            #make changes to headline
            likes = headline.likes + 1
            headline.likes = likes
            

            #modify like model to reflect
            liked_by.headline.add(headline)

            #add it to the users My Summaries
            page = Summaries(user=user, url=headline.url, comments=' ', title=headline.title, summary=headline.summary)
            page.save()
            headline.save()

    return HttpResponse(likes)


# def edit(request):
#     return request.user.username

def remove(request):
    user = request.user
    complete = False

    if request.method == 'GET':
        summary_id = request.GET['summary_id']
        if summary_id and user:
            s = Summaries.objects.get(id=summary_id, user=user)
            s.delete()
            complete = True
    return HttpResponse(complete)

nana/templates/core/base.html
{% load static %}

<!DOCTYPE html>

<html lang='en'>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="News Application">
    <meta name="author" content="Andy Pai">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen">

    <title>NANA - {% block title %}Your News{% endblock %}</title>    
    </head>

    <div class="navbar navbar-inverse">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/nana">Not Another News App</a>
      </div>
      <div class="navbar-collapse collapse navbar-inverse-collapse">
        <ul class="nav navbar-nav">
          <li {% if request.get_full_path = '/nana/' %} class="active" {% endif %}><a href="/nana/">Headlines</a></li>
          <li {% if request.get_full_path = '/nana/my_summaries/' %} class="active" {% endif %}><a href="/nana/my_summaries">My Summaries</a></li>
<!-- Drop Down List
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li class="dropdown-header">Dropdown header</li>
              <li><a href="#">Separated link</a></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>

 -->    </ul>

        {% if user.is_authenticated %}
          <ul class="nav navbar-nav navbar-right">          
            <li><a href='/nana/logout'>Logout</a></li>
          </ul>
        {% else %}
          <ul class="nav navbar-nav navbar-right">          
            <li><a href='/nana/login'>Login</a></li>
            <li><a href='/nana/register'>Register</a></li>
          </ul>
        {% endif %}

        <form class="navbar-form navbar-right" method='POST' action='/nana/search/'>
          {% csrf_token %}
          <input type="text" class="form-control col-lg-8" placeholder="Search" name='search'>
          <button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-search"></span></button>
        </form>

      </div>
    </div>

    <body>
      {% block body %}

        {% if headlines_template %}
          {% include 'core/headlines.html' %}
        {% endif %}

        {% if request.get_full_path = '/nana/my_summaries/' %}
          {% include 'core/user_summaries.html' %}
        {% endif %}

      {% endblock %}

          <hr>

      <footer style='margin-left: 12px;'>
        <p>&copy; Not Another News App  2014</p>
      </footer>


    <!-- Main jumbotron for a primary marketing message or call to action -->
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery-1.11.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>    
    <script>
        $(document).on("click", "#show", function () {
            $(this).toggleClass("active").next().slideToggle("fast");

            if ($.trim($(this).text()) === 'Show Details') {
                $(this).text('Hide Details');
            } else {
                $(this).text('Show Details');
            }
            return false;
        });
    </script>
    </body>

</html>

nana/templates/core/headlines.html
{% load static %}
{% load endless %}

<div class="jumbotron">
  <div class="container">
    <h1>Top Headlines 
      {% if category != 'Top' %}
        in <span class="text-danger">{{ category }}</span>
      {% endif %}
    </h1>
    <p>Today's headlines curated for you from various sources.</p>
    <a href="/nana/headlines/top"><button type="button" class="btn btn-success">Top</button></a>
    <a href="/nana/headlines/world"><button type="button" class="btn btn-success">World</button></a>
    <a href="/nana/headlines/us"><button type="button" class="btn btn-success">US</button></a>
    <a href="/nana/headlines/business"><button type="button" class="btn btn-success">Business</button></a>
    <a href="/nana/headlines/technology"><button type="button" class="btn btn-success">Tech</button></a>
    <a href="/nana/headlines/media"><button type="button" class="btn btn-success">Media</button></a>
    <a href="/nana/headlines/sports"><button type="button" class="btn btn-success">Sports</button></a>
    <a href="/nana/headlines/science"><button type="button" class="btn btn-success">Science</button></a>
  </div>
</div>

<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-md-12">
    {% if headlines %}
    <h3><span class="text-danger">{{ category }}</span> Headlines</h3>
        {% include page_template %}

        {% block js %}
            <script src="http://code.jquery.com/jquery-latest.js"></script>
            <script src="{{ STATIC_URL }}endless_pagination/js/endless-pagination.js"></script>
            <script>
            $.endlessPaginate({
                                paginateOnScroll: true,
                                paginateOnScrollMarign: 5
                              });
            </script>
        {% endblock %}
    {% endif %}
  </div>
</div>

<script src="{% static 'js/like.js' %}"></script>

nana/templates/core/index.html
{% block body_block %}

    <p>Welcome to the last new app you'll ever use!  Enter the details for the article you would like to read below.  We'll summarize the article for you, save it for your later reference, and even help you read it faster. Try it!  We built it so even our nana's could use it! </p>

    <form method='POST' action='/nana/add/'>
        {% csrf_token %}
        {% for field in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}<br />
        {% endfor %}

        <input type='submit' name='submit' value='Submit'>
    </form>

    {% if user.is_authenticated %}
        {% if user_summaries %}
        <h3>Latest Summaries</h3>
            {% for summary in user_summaries %}
                <ul>
                    Title: {{ summary.title }}
                    <button class="reveal">Show Details</button>
                    <div class='toggle_container' style="display: none;">
                        <div class='block'>
                            <li>Summary: {{ summary.summary }}</li>
                            <li>Comments: {{ summary.comments }}</li>
                            <li>URL: <a href='{{ headline.url }}'>{{ summary.url }}</a></li>
                            <li>Likes: {{ summary.likes }}</li>
                            <li>Added: {{ summary.added }}</li>
                        </div>
                    </div>
                </ul>
            {% endfor %}
        {% endif %}
    {% endif %}

<!-- 

        {% paginate headlines %}
        {% for headline in headlines %}
            <ul>
                Title: {{ headline.title }}
                <button class="reveal">Show Details</button>
                <div class='toggle_container'>
                    <div class='block'>
                        <li>Summary: {{ headline.summary }}</li>
                        <li>Comments: {{ headline.comments }}</li>
                        <li>URL: <a href='{{ headline.url }}'>{{ headline.url }}</a></li>
                        <li>Likes: {{ headline.likes }}</li>
                        <li>Added: {{ headline.added }}</li>
                    </div>
                </div>
            </ul>
        {% endfor %}
        {% show_pages %} -->

{% endblock %}

</html>

nana/templates/core/latest_add.html
<div class="well well-sm">    
    <h4><a class="text-primary" href="{{ s.url }}">{{ s.title }}</a>
        <span id="remove" data-sumid="{{ s.id }}" class="glyphicon glyphicon-trash pull-right" alt="Delete"></span>
    </h4>
    <button style='margin-left: 12px;' class="reveal btn btn-info btn-xs" id='show'>Show Details</button>
        <div class='toggle_container' style="display: none;">
            <div class="row">
            <div class='block col-md-11'>
              <blockquote class="pull-left">
                <h5>"{{ s.summary }}"</h5>
                <small>URL: <cite title="{{ s.url }}"><a href='{{ s.url }}'>{{ s.url }}</a></cite></small>
              </blockquote>
                Comments:  {{ s.comments }}
                <!-- <span style='margin-left: 12px;' id="edit" data-sumid="{{ summary.id }}" class="glyphicon glyphicon-pencil"></span> -->

                <br />
                Added:  {{ s.added }}
            </div>
            </div>
        </div>
</div>

nana/templates/core/login.html
{% extends 'core/base.html' %}
{% block body %}
<style>
    body{padding-top:20px;}
</style>
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Please sign in</h3>
                </div>

                <div class="panel-body">                    
                    <form accept-charset="UTF-8" role="form" method='POST' action='/nana/login/'>
                    {% csrf_token %}
                    {% if bad_details %}
                        <p class="text-danger"><strong>Incorrect username and/or password!</strong></p>
                    {% elif disabled_account %}
                        <p class="text-danger"><strong>Your Rango account is currently disabled; we can't log you in!</strong></p>
                    {% endif %}

                    <fieldset>
                        <div class="form-group">
                            <input class="form-control" placeholder="Username" name="username" value="" type="text">
                        </div>
                        <div class="form-group">
                            <input class="form-control" placeholder="Password" name="password"  value="" type="password">
                        </div>
                        <div class="checkbox">
                            <label>
                                <input name="remember" type="checkbox" value="Remember Me"> Remember Me
                            </label>
                        </div>
                        <input class="btn btn-lg btn-success btn-block" type="submit" value="Login">
                    </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
        
{% endblock %}

nana/templates/core/more_headlines.html
{% load endless %}
{% load humanize %}
{% paginate headlines %}

{% for headline, liked in headlines %}

<div class="">
    <div class="well well-sm">
        <h4>
            <a class="text-primary" href={{ headline.url }}>{{ headline.title }}</a>

            <small id="total_likes" class="text-info" style='margin-left: 12px;'>

                {% if headline.likes == 1 %}
                    {{ headline.likes }} like
                {% else %}
                    {{ headline.likes }} likes
                {% endif %}

            </small>

            {% if user.is_authenticated %}
                <span id='like_container'>
                  {% if liked %}

                    <button style='margin-left: 4px;' id="like" data-headid="{{headline.id}}" class="reveal btn btn-info disabled btn-xs" type="button"><em>Liked</em></button>
                  
                  {% else %}

                    <button style='margin-left: 4px;' id="like" data-headid="{{headline.id}}" class="reveal btn btn-info btn-xs" type="button">Like</button>

                  {% endif %}

                </span>
            {% endif %}

        </h4>

        <button style='margin-left: 12px;' class="reveal btn btn-info btn-xs" id='show'>Show Details</button>
            <div class='toggle_container' style="display: none;">
                <div class="row">
                <div class='block col-md-11'>
                  <blockquote class="pull-left">
                    <h5>"{{ headline.summary }}"</h5>
                    <small>URL: <cite title="{{ headline.url }}"><a href='{{ headline.url }}'>{{ headline.url }}</a></cite></small>
                  </blockquote>
                    Published:  {{ headline.published|naturaltime }}
                </div>
                </div>
            </div>

    </div>
</div>

{% endfor %}

{% show_more %}

nana/templates/core/register.html
{% extends 'core/base.html' %}
{% block body %}
<style>
    body{padding-top:20px;}
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Register</h3>
                </div>

                <div class="panel-body">                    
                {% if registered %}
                    Thank you for registering!  Save your summaries!
                {% else %}
                    <form accept-charset="UTF-8" role="form" method='POST' action='/nana/register/'>
                        {% csrf_token %}
                        <p class="text-danger"><strong>
                            {{ user_form.non_field_errors.as_text }}
                            {{ profile_form.non_field_errors.as_text }}
                        </strong></p>
                        {% if password_mismatch %}
                            <p class="text-danger"><strong>The two passwords you entered didn't match!</strong></p>
                        {% endif %}
                    <fieldset>
                        <div class="form-group">
                            <p class="text-danger"><strong>
                                {{ user_form.username.errors.as_text }}
                            </strong></p>
                            <label for="username">Choose Username:</label>
                            <input class="form-control" placeholder="username" name="username"  value="" type="text">
                        </div>    
                        <div class="form-group">
                            <p class="text-danger"><strong>
                                {{ user_form.email.errors.as_text }}
                            </strong></p>
                            <label for="email">Email:</label>
                            <input class="form-control" placeholder="andy@example.com" name="email"  value="" type="email">
                        </div>                        
                        <div class="form-group">
                            <p class="text-danger"><strong>
                                {{ user_form.password.errors.as_text }}
                            </strong></p>
                            <label for="password">Password:</label>
                            <input class="form-control" placeholder="password" name="password"  value="" type="password">
                        </div>
                        <div class="form-group">
                            <label for="pass_check">Re-type Password:</label>
                            <input class="form-control" placeholder="password" name="password2"  value="" type="password">
                        </div>
                        <div class="form-group">
                            <p class="text-danger"><strong>
                                {{ profile_form.website.errors.as_text }}
                            </strong></p>
                            <label for="website">Website (optional):</label>
                            <input class="form-control" placeholder="www.example.com" name="website"  value="" type="text">
                        </div>
                        <div class="form-group">
                            <p class="text-danger"><strong>
                                {{ profile_form.picture.errors.as_text }}
                            </strong></p>
                            <label for="picture">Upload Picture (optional):</label>                            
                            <input id="id_picture" name="picture" type="file">
                        </div>

                        <input class="btn btn-lg btn-success btn-block" type="submit" value="Register">
                    </fieldset>
                    </form>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
</div>
        
{% endblock %}



<!--         {% if registered %}
        Thank you for registering!
        
        {% else %}
        Register here!

        <form id='user_form' method='POST' action='nana/register' enctype='multipart/form-data'>
            {% csrf_token %}

            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <input type='submit' name='submit' value='Register'>
        </form>
        {% endif %}
    </body>
</html> -->